# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9ccd494febaf27b0ffad1c6573c5fe9ebeb2a5323d3048f923ec03ed4776dd082fa6e3cdbdda6b508590157b99aaed59a1433431bb39971900bae1f97ebdf52

test:
  secret_key_base: df4c4261f39602ce5abc1dfe6a540c9aefc19655f0557f789b97389274d77388fd7401fd5191159cc0c2fe37917c745ab3ff78998f0d960512eb121e92c5a402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
